<h1 align="center"><b>Dhvani Shah</b><br><b>Loan Default Predictor Data Cleaning and PreProcessing</b></h1>

In [1]:
import pandas as pd
import numpy as np

In [2]:
path = "D:\ML Project\Loan_default.csv.zip"
df = pd.read_csv(path)
df

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255342,8C6S86ESGC,19,37979,210682,541,109,4,14.11,12,0.85,Bachelor's,Full-time,Married,No,No,Other,No,0
255343,98R4KDHNND,32,51953,189899,511,14,2,11.55,24,0.21,High School,Part-time,Divorced,No,No,Home,No,1
255344,XQK1UUUNGP,56,84820,208294,597,70,3,5.29,60,0.50,High School,Self-employed,Married,Yes,Yes,Auto,Yes,0
255345,JAO28CPL4H,42,85109,60575,809,40,1,20.90,48,0.44,High School,Part-time,Single,Yes,Yes,Other,No,0
255346,ZTH91CGL0B,62,22418,18481,636,113,2,6.73,12,0.48,Bachelor's,Unemployed,Divorced,Yes,No,Education,Yes,0

In [3]:
print("Null : ",df.isnull().sum())
print("Duplicate : ",df.duplicated().sum())

Null :  LoanID            0
Age               0
Income            0
LoanAmount        0
CreditScore       0
MonthsEmployed    0
NumCreditLines    0
InterestRate      0
LoanTerm          0
DTIRatio          0
Education         0
EmploymentType    0
MaritalStatus     0
HasMortgage       0
HasDependents     0
LoanPurpose       0
HasCoSigner       0
Default           0
dtype: int64
Duplicate :  0

In [4]:
df = df.set_index('LoanID')

In [5]:
y = df['Default']
Cleaned_X = df.drop(columns=['Default'])

In [6]:
x = pd.get_dummies(Cleaned_X,columns=['Education','EmploymentType','MaritalStatus','HasMortgage','HasDependents','LoanPurpose','HasCoSigner'],dtype=int)
print(x.head(10))
print('default y : ',y)

            Age  Income  LoanAmount  CreditScore  MonthsEmployed  \
LoanID
I38PQUQS96   56   85994       50587          520              80
HPSK72WA7R   69   50432      124440          458              15
C1OZ6DPJ8Y   46   84208      129188          451              26
V2KKSFM3UN   32   31713       44799          743               0
EY08JDHTZP   60   20437        9139          633               8
A9S62RQ7US   25   90298       90448          720              18
H8GXPAOS71   38  111188      177025          429              80
0HGZQKJ36W   56  126802      155511          531              67
1R0N3LGNRJ   36   42053       92357          827              83
CM9L1GTT2P   40  132784      228510          480             114

            NumCreditLines  InterestRate  LoanTerm  DTIRatio  \
LoanID
I38PQUQS96               4         15.23        36      0.44
HPSK72WA7R               1          4.81        60      0.68
C1OZ6DPJ8Y               3         21.17        24      0.31
V2KKSFM3UN               3          7.07        24      0.23
EY08JDHTZP               4          6.51        48      0.73
A9S62RQ7US               2         22.72        24      0.10
H8GXPAOS71               1         19.11        12      0.16
0HGZQKJ36W               4          8.15        60      0.43
1R0N3LGNRJ               1         23.94        48      0.20
CM9L1GTT2P               4          9.09        48      0.33

            Education_Bachelor's  ...  HasMortgage_Yes  HasDependents_No  \
LoanID                            ...
I38PQUQS96                     1  ...                1                 0
HPSK72WA7R                     0  ...                0                 1
C1OZ6DPJ8Y                     0  ...                1                 0
V2KKSFM3UN                     0  ...                0                 1
EY08JDHTZP                     1  ...                0                 0
A9S62RQ7US                     0  ...                1                 1
H8GXPAOS71                     1  ...                1                 1
0HGZQKJ36W                     0  ...                0                 1
1R0N3LGNRJ                     1  ...                1                 1
CM9L1GTT2P                     0  ...                1                 1

            HasDependents_Yes  LoanPurpose_Auto  LoanPurpose_Business  \
LoanID
I38PQUQS96                  1                 0                     0
HPSK72WA7R                  0                 0                     0
C1OZ6DPJ8Y                  1                 1                     0
V2KKSFM3UN                  0                 0                     1
EY08JDHTZP                  1                 1                     0
A9S62RQ7US                  0                 0                     1
H8GXPAOS71                  0                 0                     0
0HGZQKJ36W                  0                 0                     0
1R0N3LGNRJ                  0                 0                     0
CM9L1GTT2P                  0                 0                     0

            LoanPurpose_Education  LoanPurpose_Home  LoanPurpose_Other  \
LoanID
I38PQUQS96                      0                 0                  1
HPSK72WA7R                      0                 0                  1
C1OZ6DPJ8Y                      0                 0                  0
V2KKSFM3UN                      0                 0                  0
EY08JDHTZP                      0                 0                  0
A9S62RQ7US                      0                 0                  0
H8GXPAOS71                      0                 1                  0
0HGZQKJ36W                      0                 1                  0
1R0N3LGNRJ                      1                 0                  0
CM9L1GTT2P                      0                 0                  1

            HasCoSigner_No  HasCoSigner_Yes
LoanID
I38PQUQS96               0                1
HPSK72WA7R               0                1
C1OZ6DPJ8Y               1                0
V2KKSFM3UN               1                0
EY08JDHTZP               1                0
A9S62RQ7US               0                1
H8GXPAOS71               0                1
0HGZQKJ36W               0                1
1R0N3LGNRJ               1                0
CM9L1GTT2P               0                1

[10 rows x 31 columns]
default y :  LoanID
I38PQUQS96    0
HPSK72WA7R    0
C1OZ6DPJ8Y    1
V2KKSFM3UN    0
EY08JDHTZP    0
             ..
8C6S86ESGC    0
98R4KDHNND    1
XQK1UUUNGP    0
JAO28CPL4H    0
ZTH91CGL0B    0
Name: Default, Length: 255347, dtype: int64

In [7]:
print("Rows : ",x.shape[0])
print("Columns : ",x.shape[1])
print(x.columns)

Rows :  255347
Columns :  31
Index(['Age', 'Income', 'LoanAmount', 'CreditScore', 'MonthsEmployed',
       'NumCreditLines', 'InterestRate', 'LoanTerm', 'DTIRatio',
       'Education_Bachelor's', 'Education_High School', 'Education_Master's',
       'Education_PhD', 'EmploymentType_Full-time', 'EmploymentType_Part-time',
       'EmploymentType_Self-employed', 'EmploymentType_Unemployed',
       'MaritalStatus_Divorced', 'MaritalStatus_Married',
       'MaritalStatus_Single', 'HasMortgage_No', 'HasMortgage_Yes',
       'HasDependents_No', 'HasDependents_Yes', 'LoanPurpose_Auto',
       'LoanPurpose_Business', 'LoanPurpose_Education', 'LoanPurpose_Home',
       'LoanPurpose_Other', 'HasCoSigner_No', 'HasCoSigner_Yes'],
      dtype='object')

In [8]:
print("Master ",x["Education_Master's"].sum())
print("PHD : ",x["Education_PhD"].sum())
print("Bachlor's : ",x["Education_Bachelor's"].sum())

Master  63541
PHD :  63537
Bachlor's :  64366

In [9]:
col = 'Income'

Q1 = df[col].quantile(0.25)
Q3 = df[col].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
print(f"Number of outliers in {col}: {len(outliers)}")

Number of outliers in Income: 0

In [10]:
col = 'DTIRatio'

Q1 = df[col].quantile(0.25)
Q3 = df[col].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
print(f"Number of outliers in {col}: {len(outliers)}")

Number of outliers in DTIRatio: 0

In [11]:
col = 'Age'

Q1 = df[col].quantile(0.25)
Q3 = df[col].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
print(f"Number of outliers in {col}: {len(outliers)}")

Number of outliers in Age: 0

In [12]:
col = 'LoanAmount'

Q1 = df[col].quantile(0.25)
Q3 = df[col].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
print(f"Number of outliers in {col}: {len(outliers)}")

Number of outliers in LoanAmount: 0

In [13]:
col = 'CreditScore'

Q1 = df[col].quantile(0.25)
Q3 = df[col].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
print(f"Number of outliers in {col}: {len(outliers)}")

Number of outliers in CreditScore: 0

In [14]:
print("Yes : ",df[y==1]['Default'].count())
print("No : ",df[y==0]['Default'].count())

Yes :  29653
No :  225694

In [15]:
x.describe()

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education_Bachelor's,...,HasMortgage_Yes,HasDependents_No,HasDependents_Yes,LoanPurpose_Auto,LoanPurpose_Business,LoanPurpose_Education,LoanPurpose_Home,LoanPurpose_Other,HasCoSigner_No,HasCoSigner_Yes
count,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,...,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000
mean,43.498306,82499.304597,127578.865512,574.264346,59.541976,2.501036,13.492773,36.025894,0.500212,0.252073,...,0.500014,0.499732,0.500268,0.199117,0.200895,0.199748,0.200848,0.199391,0.499892,0.500108
std,14.990258,38963.013729,70840.706142,158.903867,34.643376,1.117018,6.636443,16.969330,0.230917,0.434204,...,0.500001,0.500001,0.500001,0.399337,0.400671,0.399812,0.400636,0.399544,0.500001,0.500001
min,18.000000,15000.000000,5000.000000,300.000000,0.000000,1.000000,2.000000,12.000000,0.100000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,31.000000,48825.500000,66156.000000,437.000000,30.000000,2.000000,7.770000,24.000000,0.300000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,43.000000,82466.000000,127556.000000,574.000000,60.000000,2.000000,13.460000,36.000000,0.500000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,56.000000,116219.000000,188985.000000,712.000000,90.000000,3.000000,19.250000,48.000000,0.700000,1.000000,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
max,69.000000,149999.000000,249999.000000,849.000000,119.000000,4.000000,25.000000,60.000000,0.900000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler


import joblib



numerical_columns = ['Age','Income','LoanAmount','CreditScore','MonthsEmployed','NumCreditLines','InterestRate','DTIRatio']

Normalized_x = x.copy()

scaler = MinMaxScaler()

Normalized_x[numerical_columns] = scaler.fit_transform(x[numerical_columns])

# joblib.dump(scaler, 'scaler.pkl')

print(Normalized_x[numerical_columns].head(5))
# Normal_X['Default'] = y

# Normal_X.to_csv('Normalized_x.csv')

                 Age    Income  LoanAmount  CreditScore  MonthsEmployed  \
LoanID
I38PQUQS96  0.745098  0.525885    0.186070     0.400729        0.672269
HPSK72WA7R  1.000000  0.262461    0.487512     0.287796        0.126050
C1OZ6DPJ8Y  0.549020  0.512656    0.506892     0.275046        0.218487
V2KKSFM3UN  0.274510  0.123801    0.162446     0.806922        0.000000
EY08JDHTZP  0.823529  0.040274    0.016894     0.606557        0.067227

            NumCreditLines  InterestRate  DTIRatio
LoanID
I38PQUQS96        1.000000      0.575217    0.4250
HPSK72WA7R        0.000000      0.122174    0.7250
C1OZ6DPJ8Y        0.666667      0.833478    0.2625
V2KKSFM3UN        0.666667      0.220435    0.1625
EY08JDHTZP        1.000000      0.196087    0.7875

In [18]:
print(Normalized_x.info())
Normal_X = Normalized_x.copy()

<class 'pandas.core.frame.DataFrame'>
Index: 255347 entries, I38PQUQS96 to ZTH91CGL0B
Data columns (total 31 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Age                           255347 non-null  float64
 1   Income                        255347 non-null  float64
 2   LoanAmount                    255347 non-null  float64
 3   CreditScore                   255347 non-null  float64
 4   MonthsEmployed                255347 non-null  float64
 5   NumCreditLines                255347 non-null  float64
 6   InterestRate                  255347 non-null  float64
 7   LoanTerm                      255347 non-null  int64
 8   DTIRatio                      255347 non-null  float64
 9   Education_Bachelor's          255347 non-null  int64
 10  Education_High School         255347 non-null  int64
 11  Education_Master's            255347 non-null  int64
 12  Education_PhD                 255347 non-null  int64
 13  EmploymentType_Full-time      255347 non-null  int64
 14  EmploymentType_Part-time      255347 non-null  int64
 15  EmploymentType_Self-employed  255347 non-null  int64
 16  EmploymentType_Unemployed     255347 non-null  int64
 17  MaritalStatus_Divorced        255347 non-null  int64
 18  MaritalStatus_Married         255347 non-null  int64
 19  MaritalStatus_Single          255347 non-null  int64
 20  HasMortgage_No                255347 non-null  int64
 21  HasMortgage_Yes               255347 non-null  int64
 22  HasDependents_No              255347 non-null  int64
 23  HasDependents_Yes             255347 non-null  int64
 24  LoanPurpose_Auto              255347 non-null  int64
 25  LoanPurpose_Business          255347 non-null  int64
 26  LoanPurpose_Education         255347 non-null  int64
 27  LoanPurpose_Home              255347 non-null  int64
 28  LoanPurpose_Other             255347 non-null  int64
 29  HasCoSigner_No                255347 non-null  int64
 30  HasCoSigner_Yes               255347 non-null  int64
dtypes: float64(8), int64(23)
memory usage: 70.4+ MB
None

In [31]:
Normal_X['Default'] = y
Normal_X.to_csv('Normalized_x.csv')

In [19]:
print(Normalized_x)

                 Age    Income  LoanAmount  CreditScore  MonthsEmployed  \
LoanID
I38PQUQS96  0.745098  0.525885    0.186070     0.400729        0.672269
HPSK72WA7R  1.000000  0.262461    0.487512     0.287796        0.126050
C1OZ6DPJ8Y  0.549020  0.512656    0.506892     0.275046        0.218487
V2KKSFM3UN  0.274510  0.123801    0.162446     0.806922        0.000000
EY08JDHTZP  0.823529  0.040274    0.016894     0.606557        0.067227
...              ...       ...         ...          ...             ...
8C6S86ESGC  0.019608  0.170216    0.839522     0.438980        0.915966
98R4KDHNND  0.274510  0.273728    0.754693     0.384335        0.117647
XQK1UUUNGP  0.745098  0.517189    0.829775     0.540984        0.588235
JAO28CPL4H  0.470588  0.519330    0.226838     0.927140        0.336134
ZTH91CGL0B  0.862745  0.054949    0.055025     0.612022        0.949580

            NumCreditLines  InterestRate  LoanTerm  DTIRatio  \
LoanID
I38PQUQS96        1.000000      0.575217        36    0.4250
HPSK72WA7R        0.000000      0.122174        60    0.7250
C1OZ6DPJ8Y        0.666667      0.833478        24    0.2625
V2KKSFM3UN        0.666667      0.220435        24    0.1625
EY08JDHTZP        1.000000      0.196087        48    0.7875
...                    ...           ...       ...       ...
8C6S86ESGC        1.000000      0.526522        12    0.9375
98R4KDHNND        0.333333      0.415217        24    0.1375
XQK1UUUNGP        0.666667      0.143043        60    0.5000
JAO28CPL4H        0.000000      0.821739        48    0.4250
ZTH91CGL0B        0.333333      0.205652        12    0.4750

            Education_Bachelor's  ...  HasMortgage_Yes  HasDependents_No  \
LoanID                            ...
I38PQUQS96                     1  ...                1                 0
HPSK72WA7R                     0  ...                0                 1
C1OZ6DPJ8Y                     0  ...                1                 0
V2KKSFM3UN                     0  ...                0                 1
EY08JDHTZP                     1  ...                0                 0
...                          ...  ...              ...               ...
8C6S86ESGC                     1  ...                0                 1
98R4KDHNND                     0  ...                0                 1
XQK1UUUNGP                     0  ...                1                 0
JAO28CPL4H                     0  ...                1                 0
ZTH91CGL0B                     1  ...                1                 1

            HasDependents_Yes  LoanPurpose_Auto  LoanPurpose_Business  \
LoanID
I38PQUQS96                  1                 0                     0
HPSK72WA7R                  0                 0                     0
C1OZ6DPJ8Y                  1                 1                     0
V2KKSFM3UN                  0                 0                     1
EY08JDHTZP                  1                 1                     0
...                       ...               ...                   ...
8C6S86ESGC                  0                 0                     0
98R4KDHNND                  0                 0                     0
XQK1UUUNGP                  1                 1                     0
JAO28CPL4H                  1                 0                     0
ZTH91CGL0B                  0                 0                     0

            LoanPurpose_Education  LoanPurpose_Home  LoanPurpose_Other  \
LoanID
I38PQUQS96                      0                 0                  1
HPSK72WA7R                      0                 0                  1
C1OZ6DPJ8Y                      0                 0                  0
V2KKSFM3UN                      0                 0                  0
EY08JDHTZP                      0                 0                  0
...                           ...               ...                ...
8C6S86ESGC                      0                 0                  1
98R4KDHNND                      0                 1                  0
XQK1UUUNGP                      0                 0                  0
JAO28CPL4H                      0                 0                  1
ZTH91CGL0B                      1                 0                  0

            HasCoSigner_No  HasCoSigner_Yes
LoanID
I38PQUQS96               0                1
HPSK72WA7R               0                1
C1OZ6DPJ8Y               1                0
V2KKSFM3UN               1                0
EY08JDHTZP               1                0
...                    ...              ...
8C6S86ESGC               1                0
98R4KDHNND               1                0
XQK1UUUNGP               0                1
JAO28CPL4H               1                0
ZTH91CGL0B               0                1

[255347 rows x 31 columns]